<?php foreach($this->posts as $post): ?>
    <div class="col-md-3 col-sm-4 mix category_<?=$post['category_id']?> mix_all" style="display: block; opacity: 1; ">
        <div class="mix-inner">
            <a href="<?=$this->basePath()?>post/detail/<?=$post['id']?>">
                <img alt="" src="<?=$this->basePath()?><?=$post['thumbnail']?>" class="img-responsive">
            </a>
            <h4>
                <a href="<?=$this->basePath()?>post/detail/<?=$post['id']?>">
                    <?=$post['title']?>
                </a>
            </h4>
        </div>
    </div>
<?php endforeach; ?>