<table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tbody>
    <tr>
        <td style="background:#fff">
            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tbody>
                <tr>
                    <td valign="middle" style="padding:8px 0px" width="180">
                        <a href="<?php echo $this->base_url ?>"
                           style="text-decoration:none;color:#ffffff" title="LEEHOP"
                           target="_blank">
                            <img src="<?php echo $this->base_url.'/favicon.ico' ?>"
                                 alt="LEEHOP" border="0" height="auto" width="100%"/>
                        </a>
                    </td>
                    <td align="right" style="font-size:14px;font-family:arial">

                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td style="border-collapse:collapse;border-left:1px solid #ff6e40;border-right:1px solid #ff6e40">
            <table cellspacing="0" cellpadding="0" border="0">
                <tbody>
                <tr>
                    <td style="padding:18px 20px 20px 20px;vertical-align:middle;line-height:20px;font-family:Arial;background-color:#1a86bf;text-align:center">
                        <span style="color:#ffffff;font-size:115%;text-transform:uppercase">Xác thực yêu cầu lấy lại mật khẩu đăng nhập</span>
                    </td>
                </tr>
                <tr>
                    <td style="padding:20px 20px 12px 20px">
                        <span style="font-size:13px;color:#252525;font-family:Arial,Helvetica,sans-serif"> Chào <?php echo $this->user['first_name'].' '.$this->user['last_name']  ?>, </span>
                    </td>
                </tr>
                <tr>
                    <td style="padding:4px 20px 12px 20px">
                        <span
                            style="font-size:12px;color:#252525;font-family:Arial,Helvetica,sans-serif;line-height:18px"> Bạn đang yêu cầu lấy lại mật khẩu đăng nhập tài khoản Payment Gateway. Để hoàn tất quy trình, xin vui lòng bấm vào đường link dưới đây hoặc copy vào thanh địa chỉ trình duyệt và nhấn Enter</span>
                    </td>
                </tr>
                <tr>
                    <td style="padding:10px 20px 12px 20px">
                        <div
                            style="background:rgb(255,248,204);border:1px solid rgb(255,140,0);padding:10px;border-radius:3px 3px 0px 0px;font-size:11px;font-family:'Courier New',Courier,monospace;word-wrap:break-word"
                            align="center"><a
                                href="<?php echo $this->base_url.'/account/forgotPasswordConfirm?token='.$this->token ?>"
                                target="_blank"><?php echo $this->base_url.'/account/forgotPasswordConfirm?token='.$this->token ?></a>
                        </div>
                        <div
                            style="background-color:rgb(255,140,0);color:#ffffff;font-family:Arial,Helvetica,sans-serif;font-size:11px;padding:8px 20px;border-radius:0px 0px 3px 3px">
                            Link hết hạn lúc: <?php echo $this->expire_date ?>
                        </div>

                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>