<div class="row margin-bottom-40">
    <!-- BEGIN LATEST POSTS & CONTENT -->
    <div class="col-md-12 col-sm-12">
        <h1><?=$this->translate('Latest Posts')?></h1>
        <div class="content-page">
            <div class="filter-v1">
                <ul class="mix-filter">
                    <li data-filter="all" class="filter active">
                        <?=$this->translate('All')?>
                    </li>
                    <?php foreach($this->categories as $category) :?>
                        <li data-filter="category_<?=$category['id']?>" class="filter">
                            <?=$this->translate($category['name'])?>
                        </li>
                    <?php endforeach;?>
                </ul>
                <div class="row mix-grid thumbnails" id="posts-latest">
                    <script>
                        $(document).ready(function () {
                            getPostsLatest();
                        });
                    </script>
                </div>
                <ul class="mix-filter">
                    <li data-filter="all" class="filter active">
                        <?=$this->translate('All')?>
                    </li>
                    <?php foreach($this->categories as $category) :?>
                        <li data-filter="category_<?=$category['id']?>" class="filter">
                            <?=$this->translate($category['name'])?>
                        </li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
    </div>
    <!-- END LATEST POSTS & CONTENT -->

    <!-- BEGIN INTRODUCTION -->
    <div class="col-md-12 col-sm-12">
        <div class="content-page">
            <div class="row margin-bottom-30">
                <!-- BEGIN INFO BLOCK -->
                <div class="col-md-7">
                    <h1><?=$this->translate('Introduction')?></h1>
                    <p>Chào bạn, mình là Trần Văn Hợp - Tác giả chính và cũng là người sáng lập ra blog tranvanhop.com</p>

                    <!-- BEGIN PROGRESS BAR -->
                    <h2><?=$this->translate('My skills')?></h2>
                    <div class="front-skills" id="skills">
                        <script>
                            $(document).ready(function()
                            {
                                getSkills();
                            });
                        </script>
                    </div>
                    <!-- END PROGRESS BAR -->
                </div>
                <!-- END INFO BLOCK -->

                <!-- BEGIN CAROUSEL -->
                <div class="col-md-5 front-carousel">
                    <div id="myCarousel" class="carousel slide">
                        <!-- Carousel items -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="<?=$this->define['introduction_slide_2']?>" alt="<?=$this->define['title']?>">

                                <div class="carousel-caption">

                                </div>
                            </div>
                            <div class="item">
                                <img src="<?=$this->define['introduction_slide_3']?>"  alt="<?=$this->define['title']?>">

                                <div class="carousel-caption">

                                </div>
                            </div>
                        </div>
                        <!-- Carousel nav -->
                        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a class="carousel-control right" href="#myCarousel" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div>
                <!-- END CAROUSEL -->
            </div>
            <div class="row front-team">
                <h1><?=$this->translate('My friends')?></h1>
                <ul class="list-unstyled" id="my-friend">
                    <script>
                        $(document).ready(function()
                        {
                            getMyFriend();
                        });
                    </script>
                </ul>
            </div>

        </div>
    </div>
    <!-- END CONTENT -->
</div>
<!-- END SIDEBAR & CONTENT -->