<ul class="breadcrumb">
    <li><a href="\"><?=$this->translate('Home')?></a></li>
    <li><a href="<?=$this->basePath()?>/blog"><?=$this->translate('Blog')?></a></li>
    <li class="active"><?=$this->translate('Blog Page')?></li>
</ul>
<!-- BEGIN SIDEBAR & CONTENT -->
<div class="row margin-bottom-40">
    <!-- BEGIN CONTENT -->
    <div class="col-md-12 col-sm-12">
        <h1><?=$this->translate('Blog Page')?></h1>

        <div class="content-page">
            <div class="row">
                <!-- BEGIN LEFT SIDEBAR -->
                <div class="col-md-9 col-sm-9 blog-posts" id="blog-posts">
                    <script>
                        $(document).ready(function () {
                            getBlog(<?=$_GET['page']?>);
                        });
                    </script>
                </div>
                <!-- END LEFT SIDEBAR -->

                <!-- BEGIN RIGHT SIDEBAR -->
                <div class="col-md-3 col-sm-3 blog-sidebar">
                    <!-- CATEGORIES START -->
                    <h2 class="no-top-space"><?=$this->translate('Categories')?></h2>
                    <ul class="nav sidebar-categories margin-bottom-40">
                        <?php foreach($this->categories as $category) :?>
                            <li><a href="/blog?category_id=<?=$category['id']?>"><?=$this->translate($category['name'])?> (<?=$category['count']?>)</a></li>
                        <?php endforeach;?>
                    </ul>
                    <!-- CATEGORIES END -->

                    <!-- BEGIN RECENT NEWS -->
                    <h2>Recent News</h2>

                    <div class="recent-news margin-bottom-10">
                        <div class="row margin-bottom-10">
                            <div class="col-md-3">
                                <img class="img-responsive" alt="" src="./theme/assets/frontend/pages/img/people/img2-large.jpg">
                            </div>
                            <div class="col-md-9 recent-news-inner">
                                <h3><a href="javascript:;">Letiusto gnissimos</a></h3>

                                <p>Decusamus tiusto odiodig nis simos ducimus qui sint</p>
                            </div>
                        </div>
                        <div class="row margin-bottom-10">
                            <div class="col-md-3">
                                <img class="img-responsive" alt=""
                                     src="./theme/assets/frontend/pages/img/people/img1-large.jpg">
                            </div>
                            <div class="col-md-9 recent-news-inner">
                                <h3><a href="javascript:;">Deiusto anissimos</a></h3>

                                <p>Decusamus tiusto odiodig nis simos ducimus qui sint</p>
                            </div>
                        </div>
                        <div class="row margin-bottom-10">
                            <div class="col-md-3">
                                <img class="img-responsive" alt=""
                                     src="./theme/assets/frontend/pages/img/people/img3-large.jpg">
                            </div>
                            <div class="col-md-9 recent-news-inner">
                                <h3><a href="javascript:;">Tesiusto baissimos</a></h3>

                                <p>Decusamus tiusto odiodig nis simos ducimus qui sint</p>
                            </div>
                        </div>
                    </div>
                    <!-- END RECENT NEWS -->

                    <!-- BEGIN BLOG TALKS -->
                    <div class="blog-talks margin-bottom-30">
                        <h2>Popular Talks</h2>

                        <div class="tab-style-1">
                            <ul class="nav nav-tabs">
                                <li class="active"><a data-toggle="tab" href="#tab-1">Multipurpose</a></li>
                                <li><a data-toggle="tab" href="#tab-2">Documented</a></li>
                            </ul>
                            <div class="tab-content">
                                <div id="tab-1" class="tab-pane row-fluid fade in active">
                                    <p class="margin-bottom-10">Raw denim you probably haven't heard of them
                                        jean shorts Austin. eu banh mi, qui irure terry richardson ex squid
                                        Aliquip placeat salvia cillum iphone.</p>

                                    <p><a class="more" href="javascript:;">Read more</a></p>
                                </div>
                                <div id="tab-2" class="tab-pane fade">
                                    <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla
                                        single-origin coffee squid. aliquip jean shorts ullamco ad vinyl
                                        aesthetic magna delectus mollit. Keytar helvetica VHS salvia..</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END BLOG TALKS -->

                    <!-- BEGIN BLOG PHOTOS STREAM -->
                    <div class="blog-photo-stream margin-bottom-20">
                        <h2>Photos Stream</h2>
                        <ul class="list-unstyled">
                            <li><a href="javascript:;"><img alt=""
                                                            src="./theme/assets/frontend/pages/img/people/img5-small.jpg"></a>
                            </li>
                            <li><a href="javascript:;"><img alt=""
                                                            src="./theme/assets/frontend/pages/img/works/img1.jpg"></a>
                            </li>
                            <li><a href="javascript:;"><img alt=""
                                                            src="./theme/assets/frontend/pages/img/people/img4-large.jpg"></a>
                            </li>
                            <li><a href="javascript:;"><img alt=""
                                                            src="./theme/assets/frontend/pages/img/works/img6.jpg"></a>
                            </li>
                            <li><a href="javascript:;"><img alt=""
                                                            src="./theme/assets/frontend/pages/img/pics/img1-large.jpg"></a>
                            </li>
                            <li><a href="javascript:;"><img alt=""
                                                            src="./theme/assets/frontend/pages/img/pics/img2-large.jpg"></a>
                            </li>
                            <li><a href="javascript:;"><img alt=""
                                                            src="./theme/assets/frontend/pages/img/works/img3.jpg"></a>
                            </li>
                            <li><a href="javascript:;"><img alt=""
                                                            src="./theme/assets/frontend/pages/img/people/img2-large.jpg"></a>
                            </li>
                        </ul>
                    </div>
                    <!-- END BLOG PHOTOS STREAM -->

                    <!-- BEGIN BLOG TAGS -->
                    <div class="blog-tags margin-bottom-20">
                        <h2>Tags</h2>
                        <ul>
                            <li><a href="javascript:;"><i class="fa fa-tags"></i>OS</a></li>
                            <li><a href="javascript:;"><i class="fa fa-tags"></i>Metronic</a></li>
                            <li><a href="javascript:;"><i class="fa fa-tags"></i>Dell</a></li>
                            <li><a href="javascript:;"><i class="fa fa-tags"></i>Conquer</a></li>
                            <li><a href="javascript:;"><i class="fa fa-tags"></i>MS</a></li>
                            <li><a href="javascript:;"><i class="fa fa-tags"></i>Google</a></li>
                            <li><a href="javascript:;"><i class="fa fa-tags"></i>Facebook</a></li>
                            <li><a href="javascript:;"><i class="fa fa-tags"></i>Twitter</a></li>
                        </ul>
                    </div>
                    <!-- END BLOG TAGS -->
                </div>
                <!-- END RIGHT SIDEBAR -->
            </div>
        </div>
    </div>
    <!-- END CONTENT -->
</div>
<!-- END SIDEBAR & CONTENT -->