<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 3.4
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest (the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title><?= $this->define['title'] ?></title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta content="Metronic Shop UI description" name="description">
    <meta content="Metronic Shop UI keywords" name="keywords">
    <meta content="keenthemes" name="author">

    <meta property="og:site_name" content="-CUSTOMER VALUE-">
    <meta property="og:title" content="-CUSTOMER VALUE-">
    <meta property="og:description" content="-CUSTOMER VALUE-">
    <meta property="og:type" content="website">
    <meta property="og:image" content="-CUSTOMER VALUE-">
    <!-- link to image for socio -->
    <meta property="og:url" content="-CUSTOMER VALUE-">

    <link rel="shortcut icon" href="<?=$this->basePath()?>/favicon.ico">

    <!-- Fonts START -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css">
    <!-- Fonts END -->

    <!-- Global styles START -->
    <link href="<?= $this->basePath() ?>/theme/assets/global/plugins/font-awesome/css/font-awesome.min.css"
          rel="stylesheet">
    <link href="<?= $this->basePath() ?>/theme/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Global styles END -->

    <!-- Page level plugin styles START -->
    <link href="<?= $this->basePath() ?>/theme/assets/global/plugins/fancybox/source/jquery.fancybox.css"
          rel="stylesheet">
    <link
        href="<?= $this->basePath() ?>/theme/assets/global/plugins/carousel-owl-carousel/owl-carousel/owl.carousel.css"
        rel="stylesheet">
    <link
        href="<?= $this->basePath() ?>/theme/assets/global/plugins/slider-revolution-slider/rs-plugin/css/settings.css"
        rel="stylesheet">
    <!-- Page level plugin styles END -->

    <!-- Theme styles START -->
    <link href="<?= $this->basePath() ?>/theme/assets/global/css/components.css" rel="stylesheet">
    <link href="<?= $this->basePath() ?>/theme/assets/frontend/layout/css/style.css" rel="stylesheet">
    <link href="<?= $this->basePath() ?>/theme/assets/frontend/pages/css/style-revolution-slider.css" rel="stylesheet">
    <!-- metronic revo slider styles -->
    <link href="<?= $this->basePath() ?>/theme/assets/frontend/layout/css/style-responsive.css" rel="stylesheet">
    <link href="<?= $this->basePath() ?>/theme/assets/frontend/layout/css/themes/red.css" rel="stylesheet" id="style-color">
    <link href="<?= $this->basePath() ?>/theme/assets/frontend/pages/css/portfolio.css" rel="stylesheet">
    <link href="<?= $this->basePath() ?>/theme/assets/frontend/pages/css/gallery.css" rel="stylesheet">
    <link href="<?= $this->basePath() ?>/theme/assets/frontend/layout/css/custom.css" rel="stylesheet">
    <!-- Theme styles END -->


    <script src="<?= $this->basePath() ?>/theme/assets/global/plugins/jquery.min.js" type="text/javascript"></script>

    <script>
        var url_base = "<?=$this->basePath()?>";
    </script>
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="corporate">
<!-- BEGIN STYLE CUSTOMIZER -->
<!--<div class="color-panel hidden-sm">-->
<!--    <div class="color-mode-icons icon-color"></div>-->
<!--    <div class="color-mode-icons icon-color-close"></div>-->
<!--    <div class="color-mode">-->
<!--        <p>THEME COLOR</p>-->
<!--        <ul class="inline">-->
<!--            <li class="color-red current color-default" data-style="red"></li>-->
<!--            <li class="color-blue" data-style="blue"></li>-->
<!--        </ul>-->
<!--    </div>-->
<!--</div>-->
<!-- END BEGIN STYLE CUSTOMIZER -->

<!-- BEGIN TOP BAR -->
<div class="pre-header">
    <div class="container">
        <div class="row">
            <!-- BEGIN TOP BAR LEFT PART -->
            <div class="col-md-6 col-sm-6 additional-shop-info">
                <ul class="list-unstyled list-inline">
                    <li><i class="fa fa-phone"></i><span><?= $this->define['mobile'] ?></span></li>
                    <li><i class="fa fa-envelope-o"></i><span><?= $this->define['email'] ?></span></li>
                </ul>
            </div>
            <!-- END TOP BAR LEFT PART -->
            <!-- BEGIN TOP BAR MENU -->
            <div class="col-md-6 col-sm-6 additional-nav">
                <ul class="list-unstyled list-inline pull-right">
                    <?php foreach($this->pullRights as $pullRight): ?>
                        <li><a href="<?= $pullRight['href'] ?>"><?= $this->translate($pullRight['caption']) ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <!-- END TOP BAR MENU -->
        </div>
    </div>
</div>
<!-- END TOP BAR -->
<!-- BEGIN HEADER -->
<div class="header">
    <div class="container">
        <a class="site-logo" href="/"><img
                src="<?= $this->basePath() ?>/theme/assets/frontend/layout/img/logos/logo-corp-red.png"
                alt="LeeHop"></a>

        <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>

        <!-- BEGIN NAVIGATION -->
        <div class="header-navigation pull-right font-transform-inherit">
            <ul>
                <?php foreach ($this->menus as $menu) : ?>
                    <li class="dropdown <?= $menu['classActive'] ?>">
                        <a class="dropdown-toggle" href="<?= $menu['href'] ?>"><?= $this->translate($menu['caption']) ?></a>

                        <?php if (isset($menu['sub_menu'])) : ?>
                            <ul class="dropdown-menu">
                                <?php foreach ($menu['sub_menu'] as $subMenu) : ?>
                                    <li class="<?= $subMenu['classActive'] ?>">
                                        <a href="<?= $subMenu['href'] ?>"><?= $this->translate($subMenu['caption']) ?></a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>

                <!-- BEGIN TOP SEARCH -->
                <li class="menu-search">
                    <span class="sep"></span>
                    <i class="fa fa-search search-btn"></i>

                    <div class="search-box">
                        <form action="<?=$this->basePath()?>/post/search" method="get">
                            <div class="input-group">
                                <input type="text" placeholder="Search" class="form-control" name="q" value="<?=$this->q?>">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="submit">Search</button>
                                </span>
                            </div>
                        </form>
                    </div>
                </li>
                <!-- END TOP SEARCH -->
            </ul>
        </div>
        <!-- END NAVIGATION -->
    </div>
</div>
<!-- Header END -->

<!-- BEGIN MAIN -->
<div class="main">
    <div class="container">
        <?php $flashMessage = $this->flashMessenger()->getMessages(); ?>
        <?php if (count($flashMessage)) :?>
            <div class="row">
                <?php foreach ($flashMessage as $msg) :
                    foreach ($msg as $type => $message) : ?>
                        <li class="alert alert-<?php echo $type; ?> none">
                            <span><?= $this->translate($message); ?></span></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <?=$this->content?>
    </div>
</div>
<!--END MAIN-->

<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <!-- BEGIN COPYRIGHT -->
            <div class="col-md-6 col-sm-6 padding-top-10">
                <?=$this->translate($this->define['copyright'])?>
            </div>
            <!-- END COPYRIGHT -->
            <!-- BEGIN PAYMENTS -->
            <div class="col-md-6 col-sm-6">
                <ul class="social-footer list-unstyled list-inline pull-right">
                    <li><a target="_blank" href="<?=$this->define['facebook']?>"><i class="fa fa-facebook"></i></a></li>
                    <li><a target="_blank" href="<?=$this->define['github']?>"><i class="fa fa-github"></i></a></li>
                </ul>
            </div>
            <!-- END PAYMENTS -->
        </div>
    </div>
</div>
<!-- END FOOTER -->

<!-- Load javascripts at bottom, this will reduce page load time -->
<!-- BEGIN CORE PLUGINS (REQUIRED FOR ALL PAGES) -->
<!--[if lt IE 9]>
<script src="<?=$this->basePath()?>/theme/assets/global/plugins/respond.min.js"></script>
<![endif]-->
<script src="<?= $this->basePath() ?>/theme/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<script src="<?= $this->basePath() ?>/theme/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?= $this->basePath() ?>/theme/assets/frontend/layout/scripts/back-to-top.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->

<!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
<script src="<?= $this->basePath() ?>/theme/assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
<!-- pop up -->
<script src="<?= $this->basePath() ?>/theme/assets/global/plugins/carousel-owl-carousel/owl-carousel/owl.carousel.min.js" type="text/javascript"></script>
<!-- slider for products -->

<!-- BEGIN RevolutionSlider -->
<script src="<?= $this->basePath() ?>/theme/assets/global/plugins/slider-revolution-slider/rs-plugin/js/jquery.themepunch.revolution.min.js" type="text/javascript"></script>
<script src="<?= $this->basePath() ?>/theme/assets/global/plugins/slider-revolution-slider/rs-plugin/js/jquery.themepunch.tools.min.js" type="text/javascript"></script>
<script src="<?= $this->basePath() ?>/theme/assets/frontend/pages/scripts/revo-slider-init.js" type="text/javascript"></script>
<!-- END RevolutionSlider -->

<script src="<?= $this->basePath() ?>/theme/assets/global/plugins/jquery-mixitup/jquery.mixitup.min.js" type="text/javascript"></script>
<script src="<?= $this->basePath() ?>/theme/assets/frontend/layout/scripts/layout.js" type="text/javascript"></script>
<script src="<?= $this->basePath() ?>/theme/assets/frontend/pages/scripts/portfolio.js" type="text/javascript"></script>
<script src="<?=$this->basePath()?>/theme/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        Layout.init();
        Layout.initOWL();
        Layout.initUniform();
        RevosliderInit.initRevoSlider();
        Layout.initTwitter();
        Layout.initFixHeaderWithPreHeader(); /* Switch On Header Fixing (only if you have pre-header) */
        Layout.initNavScrolling();
        Portfolio.init();
    });
</script>

<script src="<?=$this->basePath()?>/js/utility.js"></script>
<script src="<?=$this->basePath()?>/js/home.js"></script>
<script src="<?=$this->basePath()?>/js/post.js"></script>
<script src="<?=$this->basePath()?>/js/tools.js"></script>
<script src="<?=$this->basePath()?>/js/account.js"></script>
<!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>