<table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tbody>
    <tr>
        <td style="background:#fff">
            Name :
        </td>
        <td>
            <?=$this->name?>
        </td>
    </tr>
    <tr>
        <td style="background:#fff">
            Email :
        </td>
        <td>
            <?=$this->email?>
        </td>
    </tr>
    <tr>
        <td style="background:#fff">
            Message :
        </td>
        <td>
            <?=$this->message?>
        </td>
    </tr>
    </tbody>
</table>