<?php if(isset($this->blogs['posts'])) : ?>
    <?php foreach($this->blogs['posts'] as $blog): ?>
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <img class="img-responsive" alt="" src="./theme/assets/frontend/pages/img/works/img4.jpg">
            </div>
            <div class="col-md-8 col-sm-8">
                <h2><a href="<?=$this->basePath()?>/blog/detail/<?=$blog['id']?>"><?=$blog['title']?></a></h2>
                <ul class="blog-info">
                    <li><i class="fa fa-calendar"></i> <?=date_format(date_create($blog['create_date']), 'd/m/Y')?></li>
                    <li><i class="fa fa-comments"></i> 17</li>
                    <li><i class="fa fa-tags"></i> <?=$blog['tags']?></li>
                </ul>
                <?=$blog['summary']?>
                <a href="<?=$this->basePath()?>/blog/detail/<?=$blog['id']?>" class="more">Read more <i class="icon-angle-right"></i></a>
            </div>
        </div>
        <hr class="blog-post-sep">
    <?php endforeach; ?>
<?php endif; ?>

<?php if (count($this->blogs['pagesInRange']) > 1): ?>
    <ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->blogs['previous'])): ?>
            <li>
                <a onclick="getBlog(<?= $this->blogs['previous']; ?>)">
                    Prev
                </a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <a>Prev</a>
            </li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->blogs['pagesInRange'] as $page): ?>
            <?php if ($page != $this->blogs['current']): ?>
                <li>
                    <a onclick="getBlog(<?= $page; ?>)">
                        <?= $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="active">
                    <a><?= $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->blogs['next'])): ?>
            <li>
                <a onclick="getBlog(<?= $this->blogs['next']; ?>)">
                    Next
                </a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <a>Next</a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>