<ul class="breadcrumb">
    <li><a href="\"><?=$this->translate('Home')?></a></li>
    <li><a href="<?=$this->basePath()?>/tools"><?=$this->translate('Tools')?></a></li>
    <li class="active"><?=$this->translate('Tools Detail')?></li>
</ul>
<!-- BEGIN SIDEBAR & CONTENT -->
<div class="row margin-bottom-40">
    <!-- BEGIN CONTENT -->
    <div class="col-md-12 col-sm-12">
        <h2><a href="javascript:;"><?=$this->tool['title']?></a></h2>

        <div class="row">
            <!-- BEGIN LEFT SIDEBAR -->
            <div class="col-md-12 col-sm-12 tool-item">
                <div id="tools-item">
                    <script>
                        $(document).ready(function (){
                            getToolsDetail(<?=$this->tool['id']?>)
                        });
                    </script>
                </div>
                <ul class="post-info">
                    <li><i class="fa fa-calendar"></i> <?=date_format(date_create($this->tool['create_date']), 'd/m/Y')?></li>
                    <li><i class="fa fa-comments"></i> 17</li>
                    <li><i class="fa fa-tags"></i> Metronic, Keenthemes, UI Design</li>
                </ul>

            </div>
            <!-- END LEFT SIDEBAR -->
        </div>
    </div>
    <!-- END CONTENT -->
</div>
<!-- END SIDEBAR & CONTENT -->