<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="\"><?=$this->translate('Home')?></a></li>
            <li><a href="<?=$this->basePath()?>/tools"><?=$this->translate('Tools')?></a></li>
            <li class="active"><?=$this->translate('Tools Page')?></li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
            <!-- BEGIN CONTENT -->
            <div class="col-md-12 col-sm-12">
                <h1><?=$this->translate('Tools Page')?></h1>

                <div class="content-page">
                    <div class="row">
                        <!-- BEGIN LEFT SIDEBAR -->
                        <div class="col-md-12 col-sm-12 tools-posts" id="tools">
                            <script>
                                $(document).ready(function () {
                                    getTools(<?=$_GET['page']?>);
                                });
                            </script>
                        </div>
                        <!-- END LEFT SIDEBAR -->
                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>